import type { SoundAsset } from './types/soundAsset'

export const demoSoundAssets: SoundAsset[] = [
  {
    id: 'demo-kick-grid',
    name: 'Soft Kick Grid',
    title: 'Soft Kick Grid',
    description: 'Self-generated four-on-the-floor pulse for arranging sketches.',
    category: 'drums',
    tags: ['kick', 'pulse', 'starter'],
    style: 'edm',
    durationBeats: 4,
    referenceBpm: 124,
    bpm: 124,
    key: null,
    scale: null,
    source: 'catalog-synth',
    licenseLabel: 'Royalty-free placeholder',
    preview: { tone: 'drums', accentBeats: [0, 1, 2, 3] },
  },
  {
    id: 'demo-lofi-hats',
    name: 'Dusty Hat Loop',
    title: 'Dusty Hat Loop',
    description: 'Synthetic closed-hat ticks with a relaxed lofi feel.',
    category: 'drums',
    tags: ['hat', 'lofi', 'groove'],
    style: 'lofi',
    durationBeats: 8,
    referenceBpm: 88,
    bpm: 88,
    key: null,
    scale: null,
    source: 'catalog-synth',
    licenseLabel: 'Royalty-free placeholder',
    preview: { tone: 'fx', accentBeats: [0, 0.5, 1.5, 2, 3, 3.5, 5, 6.5] },
  },
  {
    id: 'demo-bass-c-minor',
    name: 'C Minor Bass Pulse',
    title: 'C Minor Bass Pulse',
    description: 'Round synthetic bass notes for minor-key verse ideas.',
    category: 'bass',
    tags: ['bass', 'minor', 'warm'],
    style: 'rnb',
    durationBeats: 8,
    referenceBpm: 96,
    bpm: 96,
    key: 'C',
    scale: 'minor',
    source: 'catalog-synth',
    licenseLabel: 'Royalty-free placeholder',
    preview: { tone: 'bass', accentBeats: [0, 1.5, 3, 4, 6.5] },
  },
  {
    id: 'demo-pad-f-major',
    name: 'F Major Air Pad',
    title: 'F Major Air Pad',
    description: 'Breathy synthetic pad bed for cinematic intros.',
    category: 'atmosphere',
    tags: ['pad', 'cinematic', 'wide'],
    style: 'cinematic',
    durationBeats: 16,
    referenceBpm: 72,
    bpm: 72,
    key: 'F',
    scale: 'major',
    source: 'catalog-synth',
    licenseLabel: 'Royalty-free placeholder',
    preview: { tone: 'soft-pad', accentBeats: [0, 8] },
  },
  {
    id: 'demo-melody-a-pop',
    name: 'A Pop Pluck Motif',
    title: 'A Pop Pluck Motif',
    description: 'Bright generated pluck contour for hook exploration.',
    category: 'melody',
    tags: ['pluck', 'hook', 'pop'],
    style: 'pop',
    durationBeats: 8,
    referenceBpm: 112,
    bpm: 112,
    key: 'A',
    scale: 'major',
    source: 'catalog-synth',
    licenseLabel: 'Royalty-free placeholder',
    preview: { tone: 'melody', accentBeats: [0, 0.5, 1.5, 3, 4, 5.5, 7] },
  },
  {
    id: 'demo-riser-fx',
    name: 'Tiny Lift FX',
    title: 'Tiny Lift FX',
    description: 'Generated noise lift for transitions and fills.',
    category: 'fx',
    tags: ['rise', 'transition', 'noise'],
    style: null,
    durationBeats: 4,
    referenceBpm: 100,
    bpm: 100,
    key: null,
    scale: null,
    source: 'catalog-synth',
    licenseLabel: 'Royalty-free placeholder',
    preview: { tone: 'fx', accentBeats: [0, 1, 2, 3] },
  },
]
