import type { ArrangementStyle } from '../../arranger/types/music'
import type { SoundCategory, SoundClip } from '../types/soundClip'

type CatalogClip = SoundClip & {
  style: ArrangementStyle | null
}

export const SOUND_CATALOG: readonly CatalogClip[] = [
  {
    id: 'lofi-drum-loop-1',
    name: 'Lo-Fi Drum Loop',
    category: 'drums',
    style: 'lofi',
    referenceBpm: 90,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['lofi', 'laid-back', 'sampled-feel'],
  },
  {
    id: 'edm-four-on-floor',
    name: 'EDM Four-on-Floor',
    category: 'drums',
    style: 'edm',
    referenceBpm: 128,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['edm', 'driving', 'club'],
  },
  {
    id: 'rnb-pocket-groove',
    name: 'R&B Pocket Groove',
    category: 'drums',
    style: 'rnb',
    referenceBpm: 92,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['rnb', 'pocket', 'swing'],
  },
  {
    id: 'cinematic-taiko',
    name: 'Cinematic Taiko Hit',
    category: 'drums',
    style: 'cinematic',
    referenceBpm: 80,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['cinematic', 'epic', 'sparse'],
  },
  {
    id: 'pop-walking-bass',
    name: 'Pop Walking Bass',
    category: 'bass',
    style: 'pop',
    referenceBpm: 100,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['pop', 'melodic', 'warm'],
  },
  {
    id: 'lofi-sub-bass',
    name: 'Lo-Fi Sub Bass',
    category: 'bass',
    style: 'lofi',
    referenceBpm: 90,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['lofi', 'deep', 'minimal'],
  },
  {
    id: 'edm-bass-stab',
    name: 'EDM Bass Stab',
    category: 'bass',
    style: 'edm',
    referenceBpm: 128,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['edm', 'punchy', 'synth'],
  },
  {
    id: 'cinematic-strings',
    name: 'Cinematic Strings Wash',
    category: 'atmosphere',
    style: 'cinematic',
    referenceBpm: 80,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['cinematic', 'pads', 'emotional'],
  },
  {
    id: 'lofi-crackle-pad',
    name: 'Lo-Fi Crackle Pad',
    category: 'atmosphere',
    style: 'lofi',
    referenceBpm: 90,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['lofi', 'texture', 'nostalgic'],
  },
  {
    id: 'edm-synth-riser',
    name: 'EDM Synth Riser',
    category: 'atmosphere',
    style: 'edm',
    referenceBpm: 128,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['edm', 'tension', 'build'],
  },
  {
    id: 'pop-lead-hook',
    name: 'Pop Lead Hook',
    category: 'melody',
    style: 'pop',
    referenceBpm: 100,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['pop', 'catchy', 'bright'],
  },
  {
    id: 'rnb-vocal-chop',
    name: 'R&B Vocal Chop',
    category: 'melody',
    style: 'rnb',
    referenceBpm: 92,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['rnb', 'chopped', 'soulful'],
  },
  {
    id: 'lofi-rhodes-riff',
    name: 'Lo-Fi Rhodes Riff',
    category: 'melody',
    style: 'lofi',
    referenceBpm: 90,
    durationBeats: 16,
    source: 'catalog-synth',
    tags: ['lofi', 'rhodes', 'jazzy'],
  },
  {
    id: 'downlifter-sweep',
    name: 'Downlifter Sweep',
    category: 'fx',
    style: null,
    referenceBpm: 100,
    durationBeats: 4,
    source: 'catalog-synth',
    tags: ['fx', 'transition', 'sweep'],
  },
  {
    id: 'white-noise-hit',
    name: 'White Noise Hit',
    category: 'fx',
    style: null,
    referenceBpm: 100,
    durationBeats: 4,
    source: 'catalog-synth',
    tags: ['fx', 'impact', 'percussive'],
  },
  {
    id: 'transition-riser',
    name: 'Transition Riser',
    category: 'fx',
    style: null,
    referenceBpm: 100,
    durationBeats: 4,
    source: 'catalog-synth',
    tags: ['fx', 'riser', 'energy'],
  },
]

export function getClipById(id: string): SoundClip | undefined {
  return SOUND_CATALOG.find((clip) => clip.id === id)
}

export function getClipsByCategory(category: SoundCategory): SoundClip[] {
  return SOUND_CATALOG.filter((clip) => clip.category === category)
}
